


CREATE OR REPLACE PROCEDURE CHECK_ERROR(VALUE TEXT, MESSAGE TEXT DEFAULT NULL)
AS $$ BEGIN
    IF VALUE IS NULL OR LENGTH(VALUE) = 0 THEN
        RAISE EXCEPTION 'InvalidArgumentError' USING HINT = COALESCE(MESSAGE, 'The field can not be null or empty.');
    END IF;
END $$
LANGUAGE plpgsql;