-- DROP TYPE IF EXISTS "usertype" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS "admin" CASCADE;
DROP TABLE IF EXISTS "student" CASCADE;
DROP TABLE IF EXISTS "user_metadata" CASCADE;
DROP TABLE IF EXISTS "admin_role" CASCADE;
DROP TABLE IF EXISTS "admin_code" CASCADE;
DROP TABLE IF EXISTS "feature" CASCADE;
DROP TABLE IF EXISTS "user_feature" CASCADE;

CREATE TYPE "usertype" AS ENUM (
    'Admin',
    'Student',
    'Other'
);

CREATE TABLE "user" (
    "uid" VARCHAR(32) PRIMARY KEY NOT NULL,
    "display_name" TEXT,
    "email" TEXT UNIQUE,
    "phone" TEXT UNIQUE,
    "photo_url" TEXT,
    "user_type" USERTYPE NOT NULL
);

CREATE TABLE "admin" (
    "uid" VARCHAR(32) PRIMARY KEY NOT NULL,
    "role_id" SMALLINT NOT NULL,
    "code_id" SMALLINT NOT NULL
);

CREATE TABLE "student" (
    "uid" VARCHAR(32) PRIMARY KEY NOT NULL,
    "course" TEXT NOT NULL,
    "school" TEXT NOT NULL
);

CREATE TABLE "user_metadata" (
    "uid" VARCHAR(32) PRIMARY KEY NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT TIMESTAMPNOW(),
    "last_sign_in_at" TIMESTAMPTZ NOT NULL DEFAULT TIMESTAMPNOW(),
    "updated_at" TIMESTAMPTZ,
    "last_seen_at" TIMESTAMPTZ,
    "banned_until" TIMESTAMPTZ,
    "deleted_at" TIMESTAMPTZ
);

CREATE TABLE "admin_role" (
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR NOT NULL
);

CREATE TABLE "admin_code" (
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code" CHARACTER(8) NOT NULL UNIQUE
);

CREATE TABLE "feature" (
    "id" SMALLINT PRIMARY KEY NOT NULL,
    "module_name" TEXT NOT NULL UNIQUE,
    "title" TEXT NOT NULL UNIQUE,
    "class_name" TEXT,
    "method_name" TEXT
);

CREATE TABLE "user_feature" (
    "uid" VARCHAR(32) NOT NULL,
    "feature_id" INTEGER NOT NULL,
    PRIMARY KEY ("uid","feature_id")
);


ALTER TABLE "user_feature" ADD CONSTRAINT "user_feature_uid_user_uid"
    FOREIGN KEY ("uid") REFERENCES "user"("uid") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "user_feature" ADD CONSTRAINT "user_feature_feature_id_feature_id"
    FOREIGN KEY ("feature_id") REFERENCES "feature"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "student" ADD CONSTRAINT "student_uid_user_uid"
    FOREIGN KEY ("uid") REFERENCES "user"("uid") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "admin" ADD CONSTRAINT "admin_uid_user_uid"
    FOREIGN KEY ("uid") REFERENCES "user"("uid") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "admin" ADD CONSTRAINT "admin_code_id_admin_code_id"
    FOREIGN KEY ("code_id") REFERENCES "admin_code"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "admin" ADD CONSTRAINT "admin_role_id_admin_role_id"
    FOREIGN KEY ("role_id") REFERENCES "admin_role"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "user_metadata" ADD CONSTRAINT "user_metadata_uid_user_uid"
    FOREIGN KEY ("uid") REFERENCES "user"("uid") ON DELETE CASCADE ON UPDATE CASCADE;