### Create a new admin pin for an registed admin.
POST http://localhost:8080/admins/pins
Content-Type: application/json
Authorization: Bearer auth_token

{
  "email": "user6@mail.com",
  "pin": "pin"
}


### Verify an admin using pin
GET http://localhost:8080/admins/pins/user4@mail.com
Authorization: Bearer auth_token
Content-Type: text/plain

123456
