POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=AIzaSyD06VvOEIttnTUoe3JdnYKAfg_AriAtF0s
Content-Type: application/json

{
  "contents": [
    {
      "parts": [
        {
          "text": "Explain how to convert decimal 52 to binary."
        }
      ]
    }
  ]
}

###
POST https://compsci-computations.onrender.com/onboarding/items
Content-Type: application/json

{
  "source_url": "https://firebasestorage.googleapis.com/v0/b/compsci-computations.appspot.com/o/Onboarding%2Fwelcome_enim.json?alt=media&token=8811cd8b-ff1a-44bd-9a4a-0a495c445685",
  "title": "Get Started",
  "description": null,
  "type": "LOTTIE"
}

###

GET http://localhost:8080/email/send
